# TCL File Generated by Component Editor 12.1
# Wed Nov 23 14:52:05 CET 2016
# DO NOT MODIFY


# 
# GEAR_N10_R1_P4 "GEAR_N10_R1_P4" v1.0
# null 2016.11.23.14:52:05
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module GEAR_N10_R1_P4
# 
set_module_property NAME GEAR_N10_R1_P4
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME GEAR_N10_R1_P4
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GeAr_N10_R1_P4
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fullAdder.v VERILOG PATH ../Bhavin/Bhavin/GeAr_N10_R1_P4/fullAdder.v
add_fileset_file GeAr_N10_R1_P4.v VERILOG PATH ../Bhavin/Bhavin/GeAr_N10_R1_P4/GeAr_N10_R1_P4.v
add_fileset_file subAdder_R1_P4.v VERILOG PATH ../Bhavin/Bhavin/GeAr_N10_R1_P4/subAdder_R1_P4.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave in2 datab Input 10
add_interface_port nios_custom_instruction_slave out result Output 10
add_interface_port nios_custom_instruction_slave in1 dataa Input 10

