# TCL File Generated by Component Editor 12.1
# Fri Oct 14 16:21:30 CEST 2016
# DO NOT MODIFY


# 
# MULTICORE_INTERFACE "MULTICORE_INTERFACE" v1.0
# Bhavin Dhola 2016.10.14.16:21:30
# register array for communication between mother and daughter processor
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module MULTICORE_INTERFACE
# 
set_module_property DESCRIPTION "register array for communication between mother and daughter processor"
set_module_property NAME MULTICORE_INTERFACE
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Bhavin Dhola"
set_module_property DISPLAY_NAME MULTICORE_INTERFACE
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL multicore_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file MULTICORE_INTERFACE.vhd VHDL PATH MULTICORE_INTERFACE.vhd


# 
# parameters
# 
add_parameter daughter_processors INTEGER 1
set_parameter_property daughter_processors DEFAULT_VALUE 1
set_parameter_property daughter_processors DISPLAY_NAME daughter_processors
set_parameter_property daughter_processors TYPE INTEGER
set_parameter_property daughter_processors UNITS None
set_parameter_property daughter_processors ALLOWED_RANGES -2147483648:2147483647
set_parameter_property daughter_processors HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 i_address address Input 8
add_interface_port avalon_slave_0 i_av_read read Input 1
add_interface_port avalon_slave_0 i_av_write write Input 1
add_interface_port avalon_slave_0 o_wait_req waitrequest Output 1
add_interface_port avalon_slave_0 o_readdata_valid readdatavalid Output 1
add_interface_port avalon_slave_0 i_writedata writedata Input 32
add_interface_port avalon_slave_0 o_readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink i_clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink i_resetn reset_n Input 1

